export { sendEmail, type SendEmailInput, type SendEmailResult, type EmailKind } from './send-email'
export { loadOrgEmailConfig } from './load-org-email-config'
export { createGmailTransport, createTransportWithFallback } from './create-transport'
export { formatMailError } from './format-mail-error'
export { normalizeGmailAppPassword } from './normalize-app-password'
export { applyMergeFields, loadMergeFieldContext } from './merge-fields'
export { checkDailySendQuota, getDailySendLimit, getTodaySentCount } from './daily-send-quota'
export { wrapEmailHtml, type OrgPhysicalAddress, type WrapEmailHtmlOpts } from './email-wrapper'
export { isValidEmailFormat, emailFormatInvalidFlag } from './validate-email'
export { delayBetweenSendsMs, sleep } from './send-pacing'
export { applyEmailTracking, decodeClickTarget, trackingPixelDataUri } from './tracking-html'
export { recordEmailOpen, recordEmailClick } from './record-tracking'
