export { sendEmail, type SendEmailInput, type SendEmailResult, type EmailKind } from './send-email'
export { loadOrgEmailConfig } from './load-org-email-config'
export { createGmailTransport } from './create-transport'
export { applyEmailTracking, decodeClickTarget, trackingPixelDataUri } from './tracking-html'
export { recordEmailOpen, recordEmailClick } from './record-tracking'
