import type { NavItem, NavSection } from './types'

const ADMIN_ROLES: NavItem['roles'] = ['admin']
const MEMBER_ROLES: NavItem['roles'] = ['member', 'admin']

export const PRIMARY_NAV_SECTIONS: NavSection[] = [
  {
    id: 'overview',
    labelKey: 'nav.section.overview',
    items: [
      {
        id: 'dashboard',
        href: '/',
        labelKey: 'nav.dashboard',
        iconName: 'ChartBarIcon',
        roles: MEMBER_ROLES,
      },
    ],
  },
  {
    id: 'people',
    labelKey: 'nav.section.people',
    items: [
      {
        id: 'families',
        href: '/families',
        labelKey: 'nav.families',
        iconName: 'UserGroupIcon',
        roles: MEMBER_ROLES,
        shortcut: 'g f',
      },
      {
        id: 'events',
        href: '/events',
        labelKey: 'nav.events',
        iconName: 'CalendarIcon',
        roles: ADMIN_ROLES,
        shortcut: 'g e',
      },
      {
        id: 'calendar',
        href: '/calendar',
        labelKey: 'nav.calendar',
        iconName: 'CalendarDaysIcon',
        roles: ADMIN_ROLES,
      },
      {
        id: 'tasks',
        href: '/tasks',
        labelKey: 'nav.tasks',
        iconName: 'ClipboardDocumentListIcon',
        roles: ADMIN_ROLES,
        shortcut: 'g t',
      },
    ],
  },
  {
    id: 'money',
    labelKey: 'nav.section.money',
    items: [
      {
        id: 'payments',
        href: '/payments',
        labelKey: 'nav.payments',
        iconName: 'CurrencyDollarIcon',
        roles: ADMIN_ROLES,
        shortcut: 'g p',
      },
      {
        id: 'payment-disputes',
        href: '/payments/disputes',
        labelKey: 'payments.nav.disputes',
        iconName: 'ExclamationTriangleIcon',
        roles: ADMIN_ROLES,
      },
      {
        id: 'collections',
        href: '/collections',
        labelKey: 'nav.collections',
        iconName: 'BanknotesIcon',
        roles: ADMIN_ROLES,
      },
      {
        id: 'calculations',
        href: '/calculations',
        labelKey: 'nav.calculations',
        iconName: 'CalculatorIcon',
        roles: ADMIN_ROLES,
      },
      {
        id: 'projections',
        href: '/projections',
        labelKey: 'nav.projections',
        iconName: 'ChartBarSquareIcon',
        roles: ADMIN_ROLES,
      },
      {
        id: 'statements',
        href: '/statements',
        labelKey: 'nav.statements',
        iconName: 'DocumentTextIcon',
        roles: ADMIN_ROLES,
      },
    ],
  },
  {
    id: 'comms',
    labelKey: 'nav.section.comms',
    items: [
      {
        id: 'communications',
        href: '/communications',
        labelKey: 'communications.nav.main',
        iconName: 'EnvelopeOpenIcon',
        roles: ADMIN_ROLES,
        shortcut: 'g c',
      },
      {
        id: 'communications-templates',
        href: '/communications/templates',
        labelKey: 'communications.nav.templates',
        iconName: 'DocumentDuplicateIcon',
        roles: ADMIN_ROLES,
      },
      {
        id: 'communications-scheduled',
        href: '/communications/scheduled',
        labelKey: 'communications.nav.scheduled',
        iconName: 'ClockIcon',
        roles: ADMIN_ROLES,
      },
      {
        id: 'communications-jobs',
        href: '/communications/jobs',
        labelKey: 'communications.nav.jobs',
        iconName: 'QueueListIcon',
        roles: ADMIN_ROLES,
      },
      {
        id: 'communications-analytics',
        href: '/communications/analytics',
        labelKey: 'communications.nav.analytics',
        iconName: 'PresentationChartLineIcon',
        roles: ADMIN_ROLES,
      },
      {
        id: 'communications-automations',
        href: '/communications/automations',
        labelKey: 'communications.nav.automations',
        iconName: 'BoltIcon',
        roles: ADMIN_ROLES,
      },
    ],
  },
  {
    id: 'insights',
    labelKey: 'nav.section.insights',
    items: [
      {
        id: 'reports',
        href: '/reports',
        labelKey: 'nav.reports',
        iconName: 'PresentationChartBarIcon',
        roles: ADMIN_ROLES,
      },
    ],
  },
  {
    id: 'settings',
    labelKey: 'nav.section.settings',
    items: [
      {
        id: 'help',
        href: '/help',
        labelKey: 'nav.help',
        iconName: 'QuestionMarkCircleIcon',
        roles: MEMBER_ROLES,
      },
      {
        id: 'settings-email',
        href: '/settings',
        labelKey: 'settings.email',
        iconName: 'EnvelopeIcon',
        roles: ADMIN_ROLES,
        shortcut: 'g s',
        settingsTab: 'email',
      },
      {
        id: 'settings-branding',
        href: '/settings',
        labelKey: 'settings.branding',
        iconName: 'PhotoIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'branding',
      },
      {
        id: 'settings-members',
        href: '/settings',
        labelKey: 'settings.nav.members',
        iconName: 'UserGroupIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'members',
      },
      {
        id: 'settings-localization',
        href: '/settings',
        labelKey: 'settings.localization',
        iconName: 'GlobeAltIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'localization',
      },
      {
        id: 'settings-payment-plans',
        href: '/settings',
        labelKey: 'settings.nav.paymentPlans',
        iconName: 'CreditCardIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'paymentPlans',
      },
      {
        id: 'settings-event-types',
        href: '/settings',
        labelKey: 'settings.eventTypes',
        iconName: 'CalendarIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'eventTypes',
      },
      {
        id: 'settings-cycle',
        href: '/settings',
        labelKey: 'settings.cycle',
        iconName: 'CalendarDaysIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'cycle',
      },
      {
        id: 'settings-billing',
        href: '/settings',
        labelKey: 'settings.nav.billing',
        iconName: 'CreditCardIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'billing',
      },
      {
        id: 'settings-letterhead',
        href: '/settings',
        labelKey: 'settings.nav.letterhead',
        iconName: 'IdentificationIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'letterhead',
      },
      {
        id: 'settings-labels',
        href: '/settings',
        labelKey: 'settings.nav.labels',
        iconName: 'TagIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'labels',
      },
      {
        id: 'settings-kevittel',
        href: '/settings',
        labelKey: 'settings.nav.kevittel',
        iconName: 'UserGroupIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'kevittel',
      },
      {
        id: 'settings-automation',
        href: '/settings',
        labelKey: 'settings.nav.rules',
        iconName: 'Cog6ToothIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'automation',
      },
      {
        id: 'settings-activity',
        href: '/settings',
        labelKey: 'settings.nav.activity',
        iconName: 'ClockIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'activity',
      },
      {
        id: 'settings-data-export',
        href: '/settings',
        labelKey: 'settings.nav.dataExport',
        iconName: 'ArrowDownTrayIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'dataExport',
      },
      {
        id: 'settings-trash',
        href: '/settings',
        labelKey: 'settings.nav.trash',
        iconName: 'TrashIcon',
        roles: ADMIN_ROLES,
        settingsTab: 'trash',
      },
    ],
  },
]
